# Dockerfile to compress data from influx for cache
FROM ubuntu:latest
LABEL maintainer "@kuklobund"

RUN apt-get update
RUN apt-get -y install python3 python3-pip
RUN pip3 install multidict aiohttp aioredis

# Add webserver script to the Docker Image
COPY webserver.py /app/
# Copy static files (will be managed by nginx later)
COPY css /app/css
COPY js /app/js
COPY index.html /app/index.html
 
# Run the command on container startup
CMD python3 /app/webserver.py
