version: "3"  # optional since v1.27.0
services:

  b:
    build: 
      context: .
      args:
        cron_file_name: "cron_b"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.1.1
    hostname: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb_dockerdata:/var/lib/influxdb2

  redis:
    image: redis:alpine
    hostname: redis
    ports: 
      - 6379:6379

  data_compressor:
    build:
      dockerfile: Dockerfile_compressor
      context: .
    depends_on:
      - influxdb
      - redis
    volumes:
      - /etc/localtime:/etc/localtime
  
  server:
    build:
      dockerfile: Dockerfile_server
      context: .
    depends_on:
      - redis
    ports:
      - 8081:8080

volumes:
  influxdb_dockerdata:
